name: Build and Push Image

on:
    release:
        types:
            - published

jobs:
    dockerize:
        name: Dockerize and Push Image
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Build Docker Image
              run: |
                TAG=${{ github.event.release.tag_name }}
                docker build -t neo73/trekyourworld-website:${TAG} .

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}

            - name: Push Docker Image
              run: |
                TAG=${{ github.event.release.tag_name }}
                docker push neo73/trekyourworld-website:${TAG}

            - name: Log out from Docker Hub
              run: docker logout

